### ISSUE TITLE
Tách riêng phần lấy lá số

### ISSUE THREAD

**Issue by Vagabondtq** [doanguyen/lasotuvi#3]
Chào bạn,
Không biết bạn có thể tách riêng phần thuật toán lấy lá số thành PHP được không ạ :) 

Cảm ơn bạn nhiều

**Comment by doanguyen** [comment]
Hiện tại mình chưa có ý định viết lại thuật toán sử dụng PHP, mà mình sẽ ưu tiên tối ưu hóa và viết lại thuật toán tính lịch âm dương dựa vào tiết khí trước.

**Comment by Vagabondtq** [comment]
Cảm ơn bạn,

Vậy để mình sẽ chuyển code sang PHP? 
Mà như hiện tại mình đang thấy tính đúng rồi nhỉ?

**Comment by doanguyen** [comment]
Rất vui nếu bạn port sang PHP.

Hiện tại bộ code đang sử dụng thư viện chuyển ngày âm sang ngày dương của bác Hồ Ngọc Đức và không tính toán đến điểm sóc cụ thể, do đó có thể dẫn tới sai số.
