### ISSUE TITLE
Một số vị trí Triệt bị sai ạ

### ISSUE THREAD

**Issue by Nhom4CD1** [doanguyen/lasotuvi#4]
Anh ơi, giống lá số này 7h30 27/2/1992 (ÂL) Triệt đóng ở cung Điền-Quan, nhưng chạy trên trang http://lasotuvi.unitapi.com/  nó lệch qua Quan-Phúc ạ

**Comment by doanguyen** [comment]
@Nhom4CD1  Cảm ơn bạn, mình sẽ có bản sửa trong thời gian tới.

**Comment by doanguyen** [comment]
Lỗi đã được sửa, update demo tại http://doanguyen.pythonanywhere.com
thanks
